name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests"

  docker:   # 👈 must align with build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version && docker info

      # - name: Debug secrets
      #   run: echo "Username: ${{ secrets.DOCKER_USERNAME }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

     # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t 1rajendrapm/nodejs-demo-app:latest .

      # Step 5: Push Docker image
      - name: Push Docker image
        run: docker push 1rajendrapm/nodejs-demo-app:latest
