name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests"

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.#Raju1234 }}" | docker login -u "${{ secrets.rajendra3 }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.rajendra3 }}/nodejs-demo-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.rajendra3 }}/nodejs-demo-app:latest
