name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug Docker username
      - name: Debug Docker username
        run: |
          echo "Docker username: '${{ secrets.DOCKER_USERNAME }}'"
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is empty!"
            exit 1
          fi

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build --progress=plain -t rajendra3/nodejs-demo-app:latest .

      # Step 5: Push Docker image
      - name: Push Docker image
        run: docker push rajendra3/nodejs-demo-app:latest
